
package com.accenture.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://ws.accenture.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.AddResponse")
    @Action(input = "http://ws.accenture.com/Calculator/addRequest", output = "http://ws.accenture.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.MultiplyResponse")
    @Action(input = "http://ws.accenture.com/Calculator/multiplyRequest", output = "http://ws.accenture.com/Calculator/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.SubtractResponse")
    @Action(input = "http://ws.accenture.com/Calculator/subtractRequest", output = "http://ws.accenture.com/Calculator/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://ws.accenture.com/", className = "com.accenture.ws.GetHelloWorldAsStringResponse")
    @Action(input = "http://ws.accenture.com/Calculator/getHelloWorldAsStringRequest", output = "http://ws.accenture.com/Calculator/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString();

}
